// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfP6rgNzXrKDN3gjh9jd0okHgXow4-Saw',
    appId: '1:399515824553:web:79522d9bb9902c48bc54b8',
    messagingSenderId: '399515824553',
    projectId: 'hawai-52704',
    authDomain: 'hawai-52704.firebaseapp.com',
    storageBucket: 'hawai-52704.appspot.com',
    measurementId: 'G-VZ2QHPWYX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXJGUZCAtV5fVBnj1NfJrjW4BeYiso8IY',
    appId: '1:399515824553:android:d9db21fee11eed39bc54b8',
    messagingSenderId: '399515824553',
    projectId: 'hawai-52704',
    storageBucket: 'hawai-52704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd3hn1R2zz3r8piZo1ymkYu6uUA9WLonw',
    appId: '1:399515824553:ios:e965c108e46d66d3bc54b8',
    messagingSenderId: '399515824553',
    projectId: 'hawai-52704',
    storageBucket: 'hawai-52704.appspot.com',
    androidClientId: '399515824553-1bli2e82n1b5e76b271tos31r2htje3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.fab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd3hn1R2zz3r8piZo1ymkYu6uUA9WLonw',
    appId: '1:399515824553:ios:e965c108e46d66d3bc54b8',
    messagingSenderId: '399515824553',
    projectId: 'hawai-52704',
    storageBucket: 'hawai-52704.appspot.com',
    androidClientId: '399515824553-1bli2e82n1b5e76b271tos31r2htje3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.fab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5eDSIiB7D5DFk5ekIo6mTSY2Nojjh-rk',
    appId: '1:399515824553:web:cf16ea55f743a1a9bc54b8',
    messagingSenderId: '399515824553',
    projectId: 'hawai-52704',
    authDomain: 'hawai-52704.firebaseapp.com',
    storageBucket: 'hawai-52704.appspot.com',
    measurementId: 'G-V6L3HDV2WW',
  );

}