// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9pmTmwiS7rx0s-7w0Q80O2Z-cVJtP8YY',
    appId: '1:229193580396:web:91e23e60a6e8ba0da03d49',
    messagingSenderId: '229193580396',
    projectId: 'mental-health-tracking-d5b49',
    authDomain: 'mental-health-tracking-d5b49.firebaseapp.com',
    storageBucket: 'mental-health-tracking-d5b49.firebasestorage.app',
    measurementId: 'G-LNRX9SM6WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvnS6voGu3dzJouZLAZRnGrNB649d9Sig',
    appId: '1:229193580396:android:cde8ce234f9be760a03d49',
    messagingSenderId: '229193580396',
    projectId: 'mental-health-tracking-d5b49',
    storageBucket: 'mental-health-tracking-d5b49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv9zbIxOeG5A0yVG0youJJdME6uRBpgsw',
    appId: '1:229193580396:ios:7e4ba6100b9b97eca03d49',
    messagingSenderId: '229193580396',
    projectId: 'mental-health-tracking-d5b49',
    storageBucket: 'mental-health-tracking-d5b49.firebasestorage.app',
    iosBundleId: 'com.example.fab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv9zbIxOeG5A0yVG0youJJdME6uRBpgsw',
    appId: '1:229193580396:ios:7e4ba6100b9b97eca03d49',
    messagingSenderId: '229193580396',
    projectId: 'mental-health-tracking-d5b49',
    storageBucket: 'mental-health-tracking-d5b49.firebasestorage.app',
    iosBundleId: 'com.example.fab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9pmTmwiS7rx0s-7w0Q80O2Z-cVJtP8YY',
    appId: '1:229193580396:web:91e23e60a6e8ba0da03d49',
    messagingSenderId: '229193580396',
    projectId: 'mental-health-tracking-d5b49',
    authDomain: 'mental-health-tracking-d5b49.firebaseapp.com',
    storageBucket: 'mental-health-tracking-d5b49.firebasestorage.app',
    measurementId: 'G-LNRX9SM6WD',
  );

}